In [1]:
# Based on https://www.tensorflow.org/tutorials/quickstart/beginner

In [2]:
# Import
import tensorflow as tf

In [3]:
# Load data
mnist = tf.keras.datasets.mnist

In [6]:
# Divide into training and test
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
# Build a model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
# Example prediction in logits/ log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.24848408, -0.44552875, -0.04328705,  0.2986431 , -0.20161095,
         0.606484  ,  0.19981733,  0.24408078, -0.08566336, -0.6067805 ]],
      dtype=float32)

In [9]:
# Probability of the prediction being 0, 1, 2, ..., 9
tf.nn.softmax(predictions).numpy()


array([[0.11827038, 0.05908402, 0.08834082, 0.12435401, 0.07540536,
        0.1691817 , 0.11265237, 0.11775076, 0.08467547, 0.0502851 ]],
      dtype=float32)

In [10]:
# Loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
# Loss at a prediction point
loss_fn(y_train[:1], predictions).numpy()

1.776782

In [12]:
# Compiling the model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
# Fit
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0873 - accuracy: 0.9732
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0734 - accuracy: 0.9772
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0662 - accuracy: 0.9787
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0568 - accuracy: 0.9820
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0531 - accuracy: 0.9827


In [15]:
# Evaluate results
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0697 - accuracy: 0.9789 - 391ms/epoch - 1ms/step


[0.069686658680439, 0.9789000153541565]

In [17]:
# One can find the probability from the trained model, one can attach the softmax to the model
probability_model = tf.keras.Sequential([
        model,
        tf.keras.layers.Softmax()
    ])

In [18]:
# Now, the results on a sample
probability_model(x_test[:10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1.03779199e-08, 9.84376400e-11, 2.11749011e-07, 2.65900348e-06,
        3.16648999e-11, 2.81524333e-08, 4.89720442e-15, 9.99995708e-01,
        3.59135255e-09, 1.39473559e-06],
       [4.35747688e-11, 2.74716029e-07, 9.99999762e-01, 2.34018416e-10,
        6.06166431e-19, 2.62703925e-09, 2.25505781e-10, 2.65488554e-16,
        9.66460068e-09, 1.24837881e-18],
       [4.26487432e-08, 9.99790490e-01, 2.11413626e-05, 1.36529422e-06,
        3.11056647e-06, 4.89369882e-07, 8.08937841e-07, 1.28078958e-04,
        5.44771792e-05, 4.32788871e-09],
       [9.99980807e-01, 8.04022821e-11, 1.21849653e-05, 1.10388321e-09,
        4.35051639e-08, 1.38834082e-08, 8.83145731e-07, 2.58319437e-06,
        2.64401244e-11, 3.43504303e-06],
       [1.16646355e-08, 9.49921738e-12, 9.03333557e-07, 1.19227064e-08,
        9.99418855e-01, 8.40504022e-09, 2.87087563e-08, 7.62009731e-05,
        1.24088197e-08, 5.03956340e-04],
       [2.52894372e-09, 9

In [ ]:
# More advanced steps for MNIST are at: https://www.tensorflow.org/tutorials/quickstart/advanced